### ISSUE TITLE
Explorer

### ISSUE THREAD

**Issue by avive** [spacemeshos/product#68]

**Comment by lrettig** [comment]
Responding to https://github.com/spacemeshos/product/blob/master/dashboard.md:

## Visual design

The axes are not labeled. In particular it's unclear what the "x" axis is - are these all time? What unit of time? Is it interactive, or fixed?

## Data

> Real time updates from the mesh - update every 5 minutes.

Agree with @noamnelke as discussed on the call just now: polling is bad UX, especially for a "real time" application like a dashboard. We'll want something truly real time like websockets for this.

> Decentralization

I propose that we use [GINI coefficient](https://en.wikipedia.org/wiki/Gini_coefficient#Definition) for this (see also https://github.com/oliviaguest/gini), which measures inequality, but that we instead use it measure the opposite: _equality_ in block production (for now, number of blocks, and in future, block weight). So we want `1 - $gini_coefficient` where "wealth" for our purposes is number of blocks produced over some arbitrary past period, say, one week.

We may also want to factor in the _total number of smeshers_ -- since a network with five smeshers, all producing the same number of blocks, is hardly "decentralized." Maybe take a weighted sum, and give each factor 50% weight for now?
